-- Full-text search column, GIN index, trigger function, and trigger.
-- Hand-written (not generated by drizzle-kit). Fully idempotent so it is safe
-- to re-run against databases that had earlier (broken) attempts applied.

ALTER TABLE "collection_items" ADD COLUMN IF NOT EXISTS "search_vector" tsvector;
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "collection_items_search_vector_idx" ON "collection_items" USING GIN ("search_vector");
--> statement-breakpoint
CREATE OR REPLACE FUNCTION collection_items_search_vector_update() RETURNS trigger AS $$
DECLARE
  custom_text text := '';
  materials_text text := '';
  tags_text text := '';
BEGIN
  IF NEW.custom_fields IS NOT NULL THEN
    SELECT string_agg(value::text, ' ')
    INTO custom_text
    FROM jsonb_each_text(NEW.custom_fields);
  END IF;

  IF NEW.materials IS NOT NULL THEN
    SELECT array_to_string(NEW.materials, ' ') INTO materials_text;
  END IF;

  IF NEW.tags IS NOT NULL THEN
    SELECT array_to_string(NEW.tags, ' ') INTO tags_text;
  END IF;

  NEW.search_vector :=
    setweight(to_tsvector('english', coalesce(NEW.title, '')), 'A') ||
    setweight(to_tsvector('english', coalesce(NEW.description, '')), 'B') ||
    setweight(to_tsvector('english', coalesce(NEW.period, '')), 'B') ||
    setweight(to_tsvector('english', coalesce(NEW.style, '')), 'B') ||
    setweight(to_tsvector('english', coalesce(NEW.origin_country, '')), 'B') ||
    setweight(to_tsvector('english', coalesce(NEW.maker_attribution, '')), 'B') ||
    setweight(to_tsvector('english', coalesce(NEW.provenance_narrative, '')), 'C') ||
    setweight(to_tsvector('english', coalesce(materials_text, '')), 'C') ||
    setweight(to_tsvector('english', coalesce(tags_text, '')), 'C') ||
    setweight(to_tsvector('english', coalesce(custom_text, '')), 'C') ||
    setweight(to_tsvector('english', coalesce(NEW.notes, '')), 'D');

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;
--> statement-breakpoint
DROP TRIGGER IF EXISTS collection_items_search_vector_trigger ON "collection_items";
--> statement-breakpoint
CREATE TRIGGER collection_items_search_vector_trigger
  BEFORE INSERT OR UPDATE ON "collection_items"
  FOR EACH ROW
  EXECUTE FUNCTION collection_items_search_vector_update();
--> statement-breakpoint
UPDATE "collection_items" SET "search_vector" = "search_vector";
