-- Catch-up migration covering schema drift introduced via `drizzle-kit push`
-- without corresponding generated migrations. Generated by `drizzle-kit
-- generate` then made fully idempotent so it is safe on databases where any
-- subset of these changes has already been applied (including the previous
-- hand-written 0001 that added search_vector + GIN index).

-- ALTER COLUMN ... SET NOT NULL is naturally idempotent in Postgres (no error
-- if already NOT NULL). Will fail loudly if NULL rows exist — fix or delete
-- those before redeploying.
ALTER TABLE "collection_item_types" ALTER COLUMN "user_id" SET NOT NULL;
--> statement-breakpoint
ALTER TABLE "ai_analyses" ADD COLUMN IF NOT EXISTS "messages" jsonb;
--> statement-breakpoint
ALTER TABLE "collection_items" ADD COLUMN IF NOT EXISTS "search_vector" "tsvector";
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "collection_item_types_user_id_slug_idx" ON "collection_item_types" USING btree ("user_id","slug");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "collection_items_search_vector_idx" ON "collection_items" USING gin ("search_vector");
--> statement-breakpoint
ALTER TABLE "collection_item_types" DROP COLUMN IF EXISTS "is_default";
