import type { FieldSchema } from '@/types';

export interface DefaultTypeDefinition {
  name: string;
  slug: string;
  description: string;
  icon: string;
  displayOrder: number;
  fieldSchema: FieldSchema;
}

/**
 * Default collection item types cloned into every new user's account.
 * This is the single source of truth — used by registration, create-admin, and seed.
 */
export const DEFAULT_ITEM_TYPES: DefaultTypeDefinition[] = [
  {
    name: 'Furniture',
    slug: 'furniture',
    description: 'Tables, chairs, cabinets, desks, and other furniture pieces',
    icon: 'armchair',
    displayOrder: 1,
    fieldSchema: {
      fields: [
        {
          key: 'wood_type',
          label: 'Wood Type',
          type: 'multi_select',
          options: [
            'Oak',
            'Walnut',
            'Mahogany',
            'Cherry',
            'Maple',
            'Pine',
            'Rosewood',
            'Ebony',
            'Elm',
            'Satinwood',
            'Birch',
            'Teak',
            'Other',
          ],
          required: false,
          group: 'Construction',
        },
        {
          key: 'upholstery_type',
          label: 'Upholstery Type',
          type: 'select',
          options: [
            'Leather',
            'Velvet',
            'Silk',
            'Needlepoint',
            'Tapestry',
            'Linen',
            'Cotton',
            'Horsehair',
            'Cane',
            'Rush',
            'None',
          ],
          required: false,
          group: 'Construction',
        },
        {
          key: 'joinery_type',
          label: 'Joinery Type',
          type: 'select',
          options: [
            'Dovetail',
            'Mortise and Tenon',
            'Dowel',
            'Tongue and Groove',
            'Finger Joint',
            'Biscuit',
            'Nailed',
            'Screwed',
            'Unknown',
          ],
          required: false,
          group: 'Construction',
        },
        {
          key: 'hardware_type',
          label: 'Hardware Type',
          type: 'select',
          options: [
            'Brass',
            'Bronze',
            'Iron',
            'Silver',
            'Ormolu',
            'Wooden',
            'Porcelain',
            'Replacement',
            'None',
          ],
          required: false,
          group: 'Details',
        },
        {
          key: 'has_key',
          label: 'Has Key',
          type: 'boolean',
          required: false,
          group: 'Details',
        },
        {
          key: 'has_original_finish',
          label: 'Has Original Finish',
          type: 'boolean',
          required: false,
          group: 'Details',
        },
        {
          key: 'restoration_history',
          label: 'Restoration History',
          type: 'textarea',
          required: false,
          group: 'History',
        },
      ],
      measurement_presets: ['Overall', 'Seat Height', 'Arm Height', 'Leaf Extended'],
      default_materials: ['Wood', 'Veneer', 'Brass', 'Iron', 'Glass', 'Marble'],
      pdf_sections: ['Description', 'Measurements', 'Construction', 'Provenance', 'Valuation'],
    },
  },
  {
    name: 'Porcelain & Ceramics',
    slug: 'porcelain-ceramics',
    description: 'Vases, figurines, plates, and other ceramic or porcelain items',
    icon: 'cup-soda',
    displayOrder: 2,
    fieldSchema: {
      fields: [
        {
          key: 'factory_mark',
          label: 'Factory Mark',
          type: 'text',
          required: false,
          group: 'Identification',
        },
        {
          key: 'pattern_name',
          label: 'Pattern Name',
          type: 'text',
          required: false,
          group: 'Identification',
        },
        {
          key: 'glaze_type',
          label: 'Glaze Type',
          type: 'select',
          options: [
            'Overglaze',
            'Underglaze',
            'Salt Glaze',
            'Celadon',
            'Majolica',
            'Matte',
            'Crackle',
            'Unglazed',
            'Other',
          ],
          required: false,
          group: 'Construction',
        },
        {
          key: 'firing_type',
          label: 'Firing Type',
          type: 'select',
          options: [
            'Hard Paste',
            'Soft Paste',
            'Bone China',
            'Stoneware',
            'Earthenware',
            'Porcelain',
            'Terracotta',
            'Raku',
            'Unknown',
          ],
          required: false,
          group: 'Construction',
        },
        {
          key: 'base_mark_description',
          label: 'Base Mark Description',
          type: 'textarea',
          required: false,
          group: 'Identification',
        },
      ],
      measurement_presets: ['Overall', 'Rim', 'Base', 'Opening'],
      default_materials: ['Porcelain', 'Ceramic', 'Stoneware', 'Earthenware', 'Bone China'],
      pdf_sections: ['Description', 'Marks', 'Measurements', 'Provenance', 'Valuation'],
    },
  },
  {
    name: 'Textiles',
    slug: 'textiles',
    description: 'Tapestries, samplers, quilts, and decorative fabrics',
    icon: 'shirt',
    displayOrder: 3,
    fieldSchema: {
      fields: [
        {
          key: 'fiber_content',
          label: 'Fiber Content',
          type: 'multi_select',
          options: [
            'Silk',
            'Wool',
            'Cotton',
            'Linen',
            'Hemp',
            'Synthetic',
            'Gold Thread',
            'Silver Thread',
            'Mixed',
          ],
          required: false,
          group: 'Construction',
        },
        {
          key: 'weave_type',
          label: 'Weave Type',
          type: 'select',
          options: [
            'Plain',
            'Twill',
            'Satin',
            'Jacquard',
            'Tapestry',
            'Brocade',
            'Damask',
            'Velvet',
            'Embroidered',
            'Knitted',
            'Crocheted',
          ],
          required: false,
          group: 'Construction',
        },
        {
          key: 'thread_count',
          label: 'Thread Count',
          type: 'number',
          unit: 'threads/inch',
          required: false,
          group: 'Construction',
        },
        {
          key: 'colorfast',
          label: 'Colorfast',
          type: 'boolean',
          required: false,
          group: 'Condition',
        },
      ],
      measurement_presets: ['Overall', 'Visible Area', 'With Fringe'],
      default_materials: ['Silk', 'Wool', 'Cotton', 'Linen'],
      pdf_sections: ['Description', 'Construction', 'Measurements', 'Condition', 'Provenance', 'Valuation'],
    },
  },
  {
    name: 'Rugs & Carpets',
    slug: 'rugs-carpets',
    description: 'Oriental rugs, kilims, needlepoint carpets, and floor coverings',
    icon: 'rectangle-horizontal',
    displayOrder: 4,
    fieldSchema: {
      fields: [
        {
          key: 'knot_type',
          label: 'Knot Type',
          type: 'select',
          options: [
            'Turkish (Ghiordes)',
            'Persian (Senneh)',
            'Jufti',
            'Tibetan',
            'Flatweave',
            'Unknown',
          ],
          required: false,
          group: 'Construction',
        },
        {
          key: 'knots_per_inch',
          label: 'Knots Per Inch',
          type: 'number',
          unit: 'KPSI',
          required: false,
          group: 'Construction',
        },
        {
          key: 'pile_material',
          label: 'Pile Material',
          type: 'select',
          options: ['Wool', 'Silk', 'Cotton', 'Wool & Silk', 'Synthetic', 'Other'],
          required: false,
          group: 'Construction',
        },
        {
          key: 'foundation_material',
          label: 'Foundation Material',
          type: 'select',
          options: ['Cotton', 'Wool', 'Silk', 'Jute', 'Synthetic', 'Other'],
          required: false,
          group: 'Construction',
        },
        {
          key: 'selvedge_condition',
          label: 'Selvedge Condition',
          type: 'select',
          options: ['Original', 'Rewrapped', 'Damaged', 'Missing', 'N/A'],
          required: false,
          group: 'Condition',
        },
      ],
      measurement_presets: ['Overall'],
      default_materials: ['Wool', 'Silk', 'Cotton'],
      pdf_sections: ['Description', 'Construction', 'Measurements', 'Condition', 'Provenance', 'Valuation'],
    },
  },
  {
    name: 'Silver & Metalwork',
    slug: 'silver-metalwork',
    description: 'Sterling silver, silver plate, pewter, bronze, and decorative metalwork',
    icon: 'medal',
    displayOrder: 5,
    fieldSchema: {
      fields: [
        {
          key: 'hallmarks',
          label: 'Hallmarks',
          type: 'text',
          required: false,
          group: 'Identification',
        },
        {
          key: 'silver_standard',
          label: 'Silver Standard',
          type: 'select',
          options: [
            'Sterling (.925)',
            'Coin Silver (.900)',
            'Continental (.800)',
            'Britannia (.958)',
            'Silver Plate',
            'Sheffield Plate',
            'Pewter',
            'N/A',
          ],
          required: false,
          group: 'Identification',
        },
        {
          key: 'maker_mark',
          label: "Maker's Mark",
          type: 'text',
          required: false,
          group: 'Identification',
        },
        {
          key: 'weight_troy_oz',
          label: 'Weight (Troy Ounces)',
          type: 'number',
          unit: 'troy oz',
          required: false,
          group: 'Measurements',
        },
        {
          key: 'monogram',
          label: 'Monogram',
          type: 'text',
          required: false,
          group: 'Details',
        },
      ],
      measurement_presets: ['Overall', 'Base', 'Opening'],
      default_materials: ['Sterling Silver', 'Silver Plate', 'Pewter', 'Bronze', 'Brass', 'Copper'],
      pdf_sections: ['Description', 'Marks', 'Measurements', 'Provenance', 'Valuation'],
    },
  },
  {
    name: 'Paintings & Prints',
    slug: 'paintings-prints',
    description: 'Oil paintings, watercolors, lithographs, etchings, and fine art prints',
    icon: 'frame',
    displayOrder: 6,
    fieldSchema: {
      fields: [
        {
          key: 'medium',
          label: 'Medium',
          type: 'multi_select',
          options: [
            'Oil',
            'Watercolor',
            'Gouache',
            'Acrylic',
            'Tempera',
            'Pastel',
            'Charcoal',
            'Ink',
            'Pencil',
            'Mixed Media',
          ],
          required: false,
          group: 'Details',
        },
        {
          key: 'support',
          label: 'Support',
          type: 'select',
          options: [
            'Canvas',
            'Panel',
            'Paper',
            'Board',
            'Copper',
            'Ivory',
            'Vellum',
            'Linen',
            'Other',
          ],
          required: false,
          group: 'Details',
        },
        {
          key: 'frame_period',
          label: 'Frame Period',
          type: 'text',
          required: false,
          group: 'Frame',
        },
        {
          key: 'signed',
          label: 'Signed',
          type: 'boolean',
          required: false,
          group: 'Details',
        },
        {
          key: 'signature_location',
          label: 'Signature Location',
          type: 'text',
          required: false,
          group: 'Details',
        },
        {
          key: 'print_technique',
          label: 'Print Technique',
          type: 'select',
          options: [
            'Lithograph',
            'Etching',
            'Engraving',
            'Woodcut',
            'Screenprint',
            'Mezzotint',
            'Aquatint',
            'Drypoint',
            'Linocut',
            'N/A',
          ],
          required: false,
          group: 'Print Details',
        },
        {
          key: 'edition',
          label: 'Edition',
          type: 'text',
          required: false,
          group: 'Print Details',
        },
      ],
      measurement_presets: ['Sight', 'Sheet', 'Frame', 'Image'],
      default_materials: ['Oil Paint', 'Canvas', 'Paper', 'Wood Panel'],
      pdf_sections: ['Description', 'Details', 'Measurements', 'Frame', 'Provenance', 'Valuation'],
    },
  },
  {
    name: 'Books & Manuscripts',
    slug: 'books-manuscripts',
    description: 'Rare books, first editions, manuscripts, maps, and documents',
    icon: 'book-open',
    displayOrder: 7,
    fieldSchema: {
      fields: [
        {
          key: 'binding_type',
          label: 'Binding Type',
          type: 'select',
          options: [
            'Full Leather',
            'Half Leather',
            'Quarter Leather',
            'Cloth',
            'Boards',
            'Vellum',
            'Paper Wrappers',
            'Calf',
            'Morocco',
            'Pigskin',
            'Modern',
            'Unbound',
          ],
          required: false,
          group: 'Details',
        },
        {
          key: 'edition',
          label: 'Edition',
          type: 'text',
          required: false,
          group: 'Details',
        },
        {
          key: 'publisher',
          label: 'Publisher',
          type: 'text',
          required: false,
          group: 'Details',
        },
        {
          key: 'print_year',
          label: 'Print Year',
          type: 'number',
          required: false,
          group: 'Details',
        },
        {
          key: 'plates_count',
          label: 'Number of Plates',
          type: 'number',
          required: false,
          group: 'Details',
        },
        {
          key: 'condition_specifics',
          label: 'Condition Specifics',
          type: 'textarea',
          required: false,
          group: 'Condition',
        },
      ],
      measurement_presets: ['Overall'],
      default_materials: ['Paper', 'Leather', 'Vellum', 'Board', 'Cloth'],
      pdf_sections: ['Description', 'Details', 'Condition', 'Provenance', 'Valuation'],
    },
  },
];
